<?php

// app/Application/User/UseCases/V1/CreateUser.php

namespace App\Application\User\UseCases\V1;

use App\Application\User\DTOs\V1\CreateUserDTO;
use App\Domain\User\Entities\User;
use App\Domain\User\Repositories\UserRepositoryInterface;
use App\Domain\User\ValueObjects\UserEmail;
use App\Domain\User\ValueObjects\UserName;
use App\Domain\User\ValueObjects\UserPassword;
use App\Domain\User\ValueObjects\UserRoles;

/**
 * ──────────────────────────────────────────────────────────────
 * Use Case: CreateUser
 * ──────────────────────────────────────────────────────────────
 *
 * @purpose
 * Handles the process of creating a new user in the system.
 *
 * This use case acts as the *application layer* entry point for
 * user registration. It translates input data (coming from the
 * presentation layer via a DTO) into domain Value Objects,
 * applies business validation rules, and delegates persistence
 * to the UserRepositoryInterface.
 *
 * It represents a core *command* use case in the User context,
 * ensuring that the creation of a user follows all domain rules
 * and maintains consistency between layers.
 *
 * ──────────────────────────────────────────────────────────────
 *
 * @layer Application
 *
 * @pattern Command Use Case (DDD)
 *
 * @version 1.0
 *
 * @author AFLR
 */
final class CreateUser
{
    /**
     * The repository responsible for user persistence.
     *
     * The repository abstracts infrastructure details
     * (such as database or ORM) and allows the use case
     * to operate purely in domain terms.
     */
    private readonly UserRepositoryInterface $repository;

    /**
     * Constructor.
     *
     * @param  UserRepositoryInterface  $repository
     *                                               The repository implementation that handles data persistence.
     */
    public function __construct(UserRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Execute the user creation process.
     *
     * Converts the incoming DTO into validated domain Value Objects,
     * constructs a `User` domain entity, and passes it to the repository
     * for persistence. The resulting persisted user entity is then returned.
     *
     * @param  CreateUserDTO  $dto
     *                              The data transfer object containing user input data.
     * @return User
     *              Returns the fully constructed and persisted domain User entity.
     *
     * @throws \DomainException
     *                          If any business rule or domain invariant is violated during creation.
     * @throws \RuntimeException
     *                           If repository persistence fails.
     *
     * ──────────────────────────────────────────────
     * Example usage:
     * ──────────────────────────────────────────────
     * ```php
     * $dto = new CreateUserDTO(
     *     name: 'John Doe',
     *     email: 'john@example.com',
     *     password: 'secret123',
     *     roles: ['admin']
     * );
     *
     * $useCase = new CreateUser($userRepository);
     * $user = $useCase->handle($dto);
     * ```
     *
     * The `$user` returned is a Domain Entity instance representing
     * the newly created and persisted user.
     * ──────────────────────────────────────────────
     */
    public function handle(CreateUserDTO $dto): User
    {
        // Construct the domain entity using validated Value Objects.
        $user = new User(
            null, // The ID is null at this stage since it will be auto-generated by the database.
            new UserName($dto->name),
            new UserEmail($dto->email),
            new UserPassword($dto->password),
            new UserRoles($dto->roles)
        );

        // Delegate persistence to the repository layer.
        return $this->repository->create($user->toArray());
    }
}
