<?php

// src/Application/User/UseCases/V1/CreateUser.php

namespace App\Application\User\UseCases\V1;

use App\Application\User\DTOs\V1\CreateUserDTO;
use App\Domain\User\Entities\User;
use App\Domain\User\Exceptions\InvalidUserValueException;
use App\Domain\User\Repositories\UserRepositoryInterface;
use App\Domain\User\ValueObjects\UserEmail;
use App\Domain\User\ValueObjects\UserName;
use App\Domain\User\ValueObjects\UserPassword;
use App\Domain\User\ValueObjects\UserRoles;
use App\Shared\Domain\Exceptions\AlreadyExistsException;

/**
 * Use Case: CreateUser
 *
 * Application-layer use case responsible for creating a new User
 * in the system.
 *
 * Responsibilities:
 * - Receive validated input through a CreateUserDTO.
 * - Translate primitive values into domain Value Objects.
 * - Enforce domain rules, such as:
 *   - Email uniqueness.
 *   - Proper construction of User entity and its value objects.
 * - Delegate persistence to the UserRepositoryInterface.
 *
 * This use case does not know anything about HTTP, controllers,
 * or database/ORM details. It only coordinates domain logic.
 */
final class CreateUser
{
    /**
     * Repository responsible for user persistence.
     *
     * The repository abstraction hides infrastructure details
     * (e.g., Eloquent, raw SQL, external API) from the use case.
     */
    public function __construct(
        private readonly UserRepositoryInterface $repository
    ) {}

    /**
     * Execute the user creation process.
     *
     * Flow:
     *  1. Build a UserEmail value object from the DTO.
     *  2. Check if a User with that email already exists.
     *     - If yes, throw an AlreadyExistsException.
     *  3. Build the remaining value objects (UserName, UserPassword, UserRoles).
     *  4. Construct a new User aggregate (with null ID).
     *  5. Persist the User via the repository.
     *  6. Return the persisted User entity (with ID populated).
     *
     * @param  CreateUserDTO  $dto
     *                              Data Transfer Object containing the input required
     *                              to create a new user (name, email, password, roles).
     * @return User
     *              The fully constructed and persisted User domain entity.
     *
     * @throws InvalidUserValueException
     *                                   If any of the provided values (name, email, password, roles)
     *                                   violates domain rules enforced by the value objects.
     * @throws AlreadyExistsException
     *                                If a user with the same email already exists in the system.
     *
     * @example
     * php
     * $dto = new CreateUserDTO(
     *     name: 'John Doe',
     *     email: 'john@example.com',
     *     password: 'secret123',
     *     roles: ['admin']
     * );
     *
     * $useCase = new CreateUser($userRepository);
     * $user = $useCase->execute($dto);
     */
    public function execute(CreateUserDTO $dto): User
    {
        // Build email value object and check for existing user
        $emailVo = new UserEmail($dto->email);
        $existing = $this->repository->findByEmail($emailVo);

        if ($existing !== null) {
            throw new AlreadyExistsException('A user with this email already exists.');
        }

        // Construct the domain entity using validated Value Objects.
        $user = new User(
            id: null, // ID will be generated by the persistence layer.
            name: new UserName($dto->name),
            email: $emailVo,
            password: UserPassword::fromPlain($dto->password),
            roles: new UserRoles($dto->roles)
        );

        // Delegate persistence to the repository layer using the domain contract.
        return $this->repository->save($user);
    }
}
